.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ekwicoin_qt test_ekwicoin_qt
clean: FORCE
	$(MAKE) -C .. ekwicoin_qt_clean test_ekwicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_ekwicoin_qt_check
ekwicoin-qt ekwicoin-qt.exe: FORCE
	 $(MAKE) -C .. ekwicoin_qt
